from django.urls import path, include
from main.views import staff, index, module, programme, discount, student, invoice, payment, enroll, academic, service, doc
from main.views import login, dashboard, logout, register, noaccess

urlpatterns = [
    path('', index.index, name="index"),
    path('login', login.login_view, name="login"),
    path('logout', logout.logout_view, name="logout"),
    path('dashboard', dashboard.dashboard_view, name="dashboard"),
    path('register', register.register_view, name="register"),
    path('noaccess', noaccess.noaccess_view, name="noaccess"),
    path('staffs', staff.staffs_view, name="staffs"),
    path('staff/<int:id>', staff.staff_view, name="staff"),
    path('module/register', module.module_reg_view, name="module-register"),
    path('module/<int:id>', module.module_view, name="module"),
    path('modules', module.modules_view, name="modules"),
    path('programme/register', programme.programme_reg_view, name="programme-register"),
    path('programmes', programme.programmes_view, name="programmes"),
    path('programme/<int:id>', programme.programme_view, name="programme"),
    path('discounts/register', discount.discount_reg_view, name="discount-register"),
    path('discounts', discount.discounts_view, name="discounts"),
    path('discount/<int:id>', discount.discount_view, name="discount"),
    path('student/register', student.student_reg_view, name="student-register"),
    path('students', student.students_view, name="students"),
    path('students/nooffer', student.students_nooffer_view, name="students-nooffer"),
    path('student/<int:id>', student.student_view, name="student"),
    path('invoice/register', invoice.invoice_reg_view, name="invoice-register"),
    path('invoices', invoice.invoices_view, name="invoices"),
    path('invoice/<int:id>', invoice.invoice_view, name="invoice"),
    path('enroll/register', enroll.enroll_register_view, name="enroll-register"),
    path('enrolled', enroll.enrolled_view, name="enrolled"),
    path('enrolled/<int:id>', enroll.enrolled_card_view, name="enrollled-card"),
    path('api/docs', doc.doc, name="doc"),
    path('api/staff', staff.StaffsApiView.as_view()),
    path('api/staff/<int:id>', staff.StaffApiView.as_view()),
    path('api/module', module.ModulesApiView.as_view()),
    path('api/module/<int:id>', module.ModuleApiView.as_view()),
    path('api/programme', programme.ProgrammesApiView.as_view()),
    path('api/programme/<int:id>', programme.ProgrammeApiView.as_view()),
    path('api/discountandscholarship', discount.DiscountsAndScholarshipsApiView.as_view()),
    path('api/discountandscholarship/<int:id>', discount.DiscountsAndScholarshipApiView.as_view()),
    path('api/student', student.StudentsApiView.as_view()),
    path('api/student/<int:id>', student.StudentApiView.as_view()),
    path('api/invoice', invoice.InvoicesApiView.as_view()),
    path('api/invoice/<int:id>', invoice.InvoiceApiView.as_view()),
    path('api/payment', payment.PaymentsApiView.as_view()),
    path('api/payment/<int:id>', payment.PaymentApiView.as_view()),
    path('api/enroll', enroll.EnrolledStudentsApiView.as_view()),
    path('api/enroll/<int:id>', enroll.EnrolledStudentApiView.as_view()),
    path('api/academics', academic.StudentsAcademicsApiView.as_view()),
    path('api/academics/<int:id>', academic.StudentAcademicsApiView.as_view()),
    path('api/services', service.StudentServicesApiView.as_view()),
    path('api/services/<int:id>', service.StudentServiceApiView.as_view())

]
