# Generated by Django 3.0.8 on 2021-01-03 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountsAndScholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=10)),
                ('academic_year', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modules', models.ManyToManyField(blank=True, related_name='programme', to='main.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('degree', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('isInternationalStudent', models.BooleanField(default=False)),
                ('hasOffer', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('DiscountOrScholarship', models.ManyToManyField(blank=True, related_name='discounts', to='main.DiscountsAndScholarship')),
                ('programme_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmed_applied', to='main.Programme')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finance_hold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_issued', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_invoice', to='main.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_application_date', models.DateField(auto_now=True)),
                ('visa_status', models.CharField(max_length=255)),
                ('visa_exp_date', models.DateField()),
                ('inCountry', models.BooleanField(default=True)),
                ('enrolled_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.EnrolledStudent')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('academic_year', models.CharField(max_length=255)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('invoices', models.ManyToManyField(related_name='invoice', to='main.StudentInvoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_score', models.CharField(max_length=255)),
                ('academic_hold', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=255)),
                ('academic_term', models.CharField(max_length=255)),
                ('academic_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.Module')),
                ('enrolled_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics', to='main.EnrolledStudent')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='tutors',
            field=models.ManyToManyField(blank=True, related_name='module', to='main.Staff'),
        ),
        migrations.AddField(
            model_name='enrolledstudent',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.Programme'),
        ),
        migrations.AddField(
            model_name='enrolledstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='main.Student'),
        ),
    ]
