# Generated by Django 3.0.8 on 2021-02-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210201_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='it_department_access',
            field=models.BooleanField(default=False),
        ),
    ]
