# Generated by Django 3.0.8 on 2021-02-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_staff_it_department_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='director_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='student_admission_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='student_finance_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='student_office_department_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='student_visa_access',
            field=models.BooleanField(default=False),
        ),
    ]
