# Generated by Django 3.0.8 on 2021-02-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210201_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
