# Generated by Django 3.0.8 on 2021-02-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_programme_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountsandscholarship',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
